{
 "title": "Money",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Account",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"home\",\n    tag: \"name\",\n    predicate: (r) => r._measurement == \"account\",\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Account History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "measurement": "account",
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"] =~ /^${Account}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Account$/" }
     ]
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "account",
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"] =~ /^expenses:/)\n  |> aggregateWindow(every: 1mo, fn: spread, createEmpty: true)\n  |> filter(fn: (r) => r._value > 0)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^expenses:/" },
      { "condition": "AND", "key": "balance", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  { "title": "Budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Daily Checking Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"]=~ /checking/)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> filter(fn: (r) => r._value > 0)"
    },
    {
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"]=~ /hecking/)\n  |> group(columns: [])\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> filter(fn: (r) => r._value > 0)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Daily Savings Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"]=~ /savings/)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> filter(fn: (r) => r._value > 0)"
    },
    {
     "query": "from(bucket: \"home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"]=~ /savings/)\n  |> group(columns: [])\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> filter(fn: (r) => r._value > 0)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Checking",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "account",
     "query": "from(bucket: \"home\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"]=~ /checking/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._value > 0)\n  |> last()\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "account",
     "query": "from(bucket: \"home\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"account\")\n  |> filter(fn: (r) => r[\"name\"]=~ /savings/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._value > 0)\n  |> last()\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}