name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true

      - name: Install dependencies
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Test
        run: ginkgo ./...